config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    resources :comments
  end
  resources :contacts
  devise_for :users, :controllers => {registrations: 'registrations'}
  root to: 'pages#index'
  get 'pages/contact'
  get 'pages/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/contact.rb
class Contact < ActiveRecord::Base
    validates_presence_of :name
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :articles
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.paginate(page: params[:page], per_page: 1)
    @last5 = Article.last(5)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = current_user.articles.build
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(params[:comment].permit(:body))
        @comment.user_id = current_user.id if current_user
        if @comment.save
            redirect_to article_path(@article), notice: "your comment "
        else 
            redirect_to 'new'
    end
end

def update
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
   
    if @comment.update(params[:comment].permit(:body))
    redirect_to article_path(@article), notice: "Your comment has been updated."
    else
    render 'edit'
    end
   
    end

    def edit
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
    end

    def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article), notice: 'your comment has been destroyed'
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
        @contact = Contact.new
    end

    def create
        @contact = Contact.new(contact_params)

        if @contact.save
            redirect_to root_path
            name= params[:contact][:name]
            email=params[:contact][:email]
            message=params[:contact][:message]
            ContactMailer.contact_email(name, email, message).deliver
            flash[:success]="thanks for message"
        else
            redirect_to pages_contact_path
            flash[:danger]="there is a problem. please fill all the fields"
        end
    end

    private
    def contact_params
        params.require(:contact).permit(:name, :email, :message)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @articles=Article.last(2)
  end

  def contact
    @contact = Contact.new
  end

  def about
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    def sign_up_params
        params.require(:user).permit(
            :email,
            :password,
            :password_confirmation,
            :username,
            :firstname,
            :lastname,
            :article
        )
    end

    def account_update_params
        params.require(user).permit(
            :email,
            :password,
            :password_confirmation,
            :current_password,
            :username,
            :firstname,
            :lastname
        )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="row">
 <!-- Blog article Content Column -->
 <div class="col-lg-8">
<% @articles.each do |article| %>
 <!-- Blog article -->
 <!-- Title -->
 <h4 style="font-size: 45.5px;"><%= link_to article.title, article %></h4>
 <!-- Date/Time -->
 <p><span class="glyphicon glyphicon-time"></span>
 </p>

 <!-- Author -->
 <p>
 Article By:<strong> <%= article.user.username %></strong>
 </p>
 <hr>
 <!-- articleed Comments -->
 <!-- Comment -->
<% end %>
<%= link_to "New article", new_article_path, class: "btn btn-default btn-xs" %>
 </div>

2 
<!-- Blog Sidebar Widgets Column -->
<div class="col-md-4">
 <div class="well">
 <h4>Recent articles</h4>
 <% @last5.each do |p| %>
 Created by: <%= p.user.username %><br />
 <strong><%= link_to p.title, p %></strong>
 <p><%= truncate(p.body) %></p>
 <% end %>
 </div>
</div>
</div>
<%=will_paginate @articles%>
<br>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<div class="row">
 <!-- Blog Post Content Column -->
 <div class="col-lg-8">
 <!-- Blog Post -->
 <!-- Title -->
 <h1 style="font-size: 34.5px;">
 <%= @article.title %>
 </h1>
 <!-- Author -->
 <p class="lead">
 <%= @article.user.email %>
 </p>
 <hr>
 <!-- Date/Time -->
 <p><span class="glyphicon glyphicon-time"></span> Was Posted:

 <hr>
 <!-- Preview Image -->

 <hr>
 <!-- Post Content -->

 <hr>
 <!-- Blog Comments -->

 <%= @article.body %>
 <!-- Comments Form -->

 <%= render 'comments/form' %>
 <div class="well">
 

 <%= render @article.comments%>
<h4>blah blah</h4>
 </div>
 <hr>
 <!-- Posted Comments -->
 <!-- Comment -->
 </div>
 <!-- Blog Sidebar Widgets Column -->
 <div class="col-md-4">
 <!-- Blog Search Well -->

 <!-- Blog Categories Well -->

 <!-- Side Widget Well -->
 <div class="well">
 <h4>Recent Posts</h4>

 </div>
 </div>
</div>
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<div class="media">
    <div class ="pull-left">
        <%="#{comment.user.try(:email) }" %>
        <%=comment.body%>
    </div>
    <div class="media-body">
        <p class ="media-heading pull-right">
        <%= "#{time_ago_in_words(comment.created_at)} ago" if comment.created_at %>
        
        </p>
    </div>
</div>

<%=link_to "Edit", edit_article_comment_path(comment.article)%>
<%=link_to "Delete", [comment.article, comment], method: :delete, data: {confirm: "Are you sure"}%>

app/views/comments/_form.html.erb
<%=simple_form_for ([@article, @article.comments.build]) do |f|%>
<%= f.input :body%>
<%=f.submit "Post your comment"%>
<%end%>

app/views/comments/edit.html.erb
<h1>edit coment</h1>
<%= simple_form_for([@article, @comment]) do |f|%>
<%=f.input :body%>
<%=f.submit%>
<%end%>

app/views/layouts/_foot.html.erb
<footer class="footer-distributed">
    <div class="footer-left">
    <h3>Company<span>logo</span></h3>
    <p class="footer-links">
    <a href="#">Home</a>
    ·
    <a href="#">Blog</a>
    ·
    <a href="#">Pricing</a>
    ·
    <a href="#">About</a>
    ·
    <a href="#">Faq</a>
    ·
    <a href="#">Contact</a>
    </p>
    <p class="footer-company-name">Company Name &copy; 2015</p>
        <div class="footer-icons">
        <a href="#"><i class="fa fa-facebook"></i></a>
        <a href="#"><i class="fa fa-twitter"></i></a>
        <a href="#"><i class="fa fa-linkedin"></i></a>
        <a href="#"><i class="fa fa-github"></i></a>

        </div>
    </div>
    <div class="footer-right">
    <p>Contact Us</p>
        <form action="#" method="post">
            <input type="text" name="email" placeholder="Email" />
            <textarea name="message" placeholder="Message"></textarea>
            <button>Send</button>
        </form>
    </div>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light"> 
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="navbar-brand" href="#">Navbar</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>      
    </ul>
  
    <div class = "nav navbar-nav navbar-right">
      <li class="nav-item active">
          
          <li class="nav-item"><%= link_to "Contact", pages_contact_path %></li></li>
          <li class="nav-item"><%= link_to "About us", pages_about_path %></li></li>
           <li><%= link_to "View Articles", articles_path %></li>
          <li class="nav-item"><%= link_to "Create article", new_article_path %></li></li>
          <li class="nav-item"><%= link_to "sign up", new_user_registration_path if !current_user %></li></li>
          <li class="nav-item"><%= link_to "sign in", new_user_session_path if !current_user %></li></li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <%if current_user %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
            </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#"><%= link_to "sign out", destroy_user_session_path, method: :delete %></a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item"><%= link_to "edit my profile", edit_user_registration_path %></li></a>
          </div>
        </li>
        <%end%>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Emailer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <%=render'layouts/nav'%>
    <%=bootstrap_flash %>
    <div class = 'container'>
      <%= yield %>
    </div>
      <%=render'layouts/foot'%>

  </body>

</html>

app/views/pages/_mailer.html.erb
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="well">
            <%= simple_form_for(@contact) do |f|%>
            <%= f.input :name %>
            <%= f.input :email%>
            <%= f.input :message%>
            <%= f.submit "get in touch", class: "btn btn-info"%>
            <%end%>
        </div>
    </div>
</div>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>
<%= render 'pages/mailer' %>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>
<% @articles.each do |a|%><strong>
<%= a.user.email%>
<strong><%=link_to a.title, a%>
<a><%=truncate(a.body)%></a>
<% end %>